version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
#    environment:
    depends_on:
      - app-db

  app-db:
    image: 'postgres'
    container_name: app-db
    expose:
      - '5432'
    environment:
      POSTGRES_DB: motorcycleDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 267115
