services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
#    environment:
    depends_on:
      - app-db

  app-db:
    image: 'postgres'
    container_name: app-db
    expose:
      - '5432'
    environment:
      POSTGRES_DB: motorcycleDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 267115

#
#  zookeeper:
#    container_name: zookeeper
#    image: confluentinc/cp-zookeeper:7.4.0
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#
#  kafka:
#    container_name: kafka
#    image: confluentinc/cp-kafka:7.4.0
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    depends_on:
      - app-db